apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: merneat
spec:
  volumeName: mongodb-pv
  storageClassName: standered
  accessModes: 
    - ReadWriteOnce
  resources:
    requests: 
      storage: 1Gi