apiVersion: apps/v1
kind: Deployment
metadata:
  name: merneat-frontend
  namespace: merneat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: client
          image: radhe2003/merneat_frontend:01
          ports:
            - containerPort: 5000
---            
apiVersion: v1
kind: Service
metadata:
  name: client-service
  namespace: merneat
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: frontend